import {
  LayoutDashboard, Users, ShoppingBag, Car, Pill, Box,
  PackageSearch, Megaphone, Receipt, Settings2, Zap,
  AppWindow, Store, Bike, Ticket, BellRing, BanknoteIcon,
  Banknote, Shield, Navigation, Search,
  FolderTree, Star, Layers, BadgeCheck, ArrowDownToLine, AlertTriangle,
  Bus, Wallet, CreditCard, Bug, FileText, Lock,
  Heart, QrCode, FlaskConical, Webhook, Link2,
  Radio, BarChart2, HelpCircle, MessageCircle, ToggleLeft, Truck,
  KeyRound,
  type LucideIcon,
} from "lucide-react";

export type SearchCategory = "Pages" | "Settings" | "Actions" | "Users" | "Orders" | "Rides";

export interface SearchEntry {
  id: string;
  title: string;
  subtitle?: string;
  keywords: string[];
  urduKeywords: string[];
  romanUrduKeywords: string[];
  category: SearchCategory;
  /** Destination path; may include query params for pre-filtered views */
  path?: string;
  icon: LucideIcon;
  group: string;
  hint?: string;
}

export const SEARCH_INDEX: SearchEntry[] = [

  /* ════════════════════ PAGES — Navigation ════════════════════ */
  {
    id: "page-dashboard",
    title: "Dashboard",
    subtitle: "Overview: stats, revenue, recent activity",
    keywords: ["dashboard", "overview", "home", "stats", "analytics", "summary", "revenue", "activity", "kpis"],
    urduKeywords: ["ڈیش بورڈ", "جائزہ", "گھر", "اعداد و شمار", "آمدنی", "خلاصہ"],
    romanUrduKeywords: ["dashboard", "jaiza", "ghar", "aadad", "aamadni", "khulasa", "overview"],
    category: "Pages", path: "/dashboard", icon: LayoutDashboard, group: "Pages",
  },
  {
    id: "page-orders",
    title: "Orders",
    subtitle: "All customer orders",
    keywords: ["orders", "order list", "deliveries", "shopping", "mart orders", "food orders"],
    urduKeywords: ["آرڈرز", "آرڈر", "ڈیلیوریاں", "خریداری"],
    romanUrduKeywords: ["orders", "order", "deliveries", "delivery", "kharidaari"],
    category: "Pages", path: "/orders", icon: ShoppingBag, group: "Pages",
  },
  {
    id: "page-rides",
    title: "Rides",
    subtitle: "Taxi, bike, rickshaw bookings",
    keywords: ["rides", "ride bookings", "taxi", "car", "bike", "rickshaw", "transport", "active rides"],
    urduKeywords: ["سواریاں", "سواری", "ٹیکسی", "گاڑی", "بائیک", "رکشہ"],
    romanUrduKeywords: ["sawariyan", "sawari", "taxi", "gaari", "bike", "riksha", "transport"],
    category: "Pages", path: "/rides", icon: Car, group: "Pages",
  },
  {
    id: "page-van",
    title: "Van Service",
    subtitle: "Van and minibus ride bookings",
    keywords: ["van", "van service", "minibus", "school van", "minivan", "shared ride"],
    urduKeywords: ["وین سروس", "وین", "منی بس"],
    romanUrduKeywords: ["van service", "van", "minibus", "shared ride"],
    category: "Pages", path: "/van", icon: Bus, group: "Pages",
  },
  {
    id: "page-pharmacy",
    title: "Pharmacy",
    subtitle: "Medicine orders management",
    keywords: ["pharmacy", "medicine", "drugs", "health", "medical orders", "prescriptions", "dawa"],
    urduKeywords: ["فارمیسی", "دوائیں", "صحت", "طبی آرڈرز", "دوا"],
    romanUrduKeywords: ["pharmacy", "dawayein", "sehat", "tibbi", "medicine", "dawai"],
    category: "Pages", path: "/pharmacy", icon: Pill, group: "Pages",
  },
  {
    id: "page-parcels",
    title: "Parcels",
    subtitle: "Parcel and courier bookings",
    keywords: ["parcels", "courier", "package", "delivery", "shipment", "parcel bookings"],
    urduKeywords: ["پارسل", "کورئیر", "پیکج", "شپمنٹ"],
    romanUrduKeywords: ["parcel", "courier", "package", "delivery", "shipment"],
    category: "Pages", path: "/parcel", icon: Box, group: "Pages",
  },
  {
    id: "page-live-map",
    title: "Live Riders Map",
    subtitle: "Real-time rider GPS tracking",
    keywords: ["live map", "live riders", "tracking", "gps", "location", "real-time", "map", "rider locations"],
    urduKeywords: ["لائیو میپ", "رائیڈرز کا نقشہ", "ٹریکنگ", "جی پی ایس"],
    romanUrduKeywords: ["live map", "naqsha", "tracking", "gps", "location", "real-time"],
    category: "Pages", path: "/live-riders-map", icon: Navigation, group: "Pages",
  },
  {
    id: "page-users",
    title: "Users",
    subtitle: "All registered app users",
    keywords: ["users", "customers", "accounts", "profiles", "registered users", "members", "user permissions"],
    urduKeywords: ["صارفین", "گاہک", "اکاؤنٹ", "پروفائل"],
    romanUrduKeywords: ["sarifeen", "gaahak", "account", "profile", "members"],
    category: "Pages", path: "/users", icon: Users, group: "Pages",
  },
  {
    id: "page-vendors",
    title: "Vendors",
    subtitle: "Vendor stores and restaurants",
    keywords: ["vendors", "stores", "shops", "restaurants", "merchants", "seller", "vendor management"],
    urduKeywords: ["وینڈرز", "دکانیں", "ریستوران", "تاجر", "دکاندار"],
    romanUrduKeywords: ["vendors", "dukaan", "restaurant", "taajir", "dukandaar"],
    category: "Pages", path: "/vendors", icon: Store, group: "Pages",
  },
  {
    id: "page-riders",
    title: "Riders",
    subtitle: "Delivery and ride drivers",
    keywords: ["riders", "drivers", "delivery agents", "bikers", "couriers", "rider management"],
    urduKeywords: ["رائیڈرز", "ڈرائیور", "ڈیلیوری ایجنٹ"],
    romanUrduKeywords: ["riders", "drivers", "delivery agent", "biker"],
    category: "Pages", path: "/riders", icon: Bike, group: "Pages",
  },
  {
    id: "page-products",
    title: "Products",
    subtitle: "Product catalog and inventory",
    keywords: ["products", "items", "catalog", "inventory", "stock", "listings", "sku"],
    urduKeywords: ["مصنوعات", "اشیاء", "کیٹلاگ", "اسٹاک"],
    romanUrduKeywords: ["masnoaat", "ashiya", "catalog", "stock", "inventory"],
    category: "Pages", path: "/products", icon: PackageSearch, group: "Pages",
  },
  {
    id: "page-categories",
    title: "Categories",
    subtitle: "Product and service categories",
    keywords: ["categories", "category", "folders", "types", "groups", "classification"],
    urduKeywords: ["زمرے", "قسم", "گروپ"],
    romanUrduKeywords: ["zamray", "qism", "group", "categories"],
    category: "Pages", path: "/categories", icon: FolderTree, group: "Pages",
  },
  {
    id: "page-promotions",
    title: "Promotions Hub",
    subtitle: "Manage all promotions, banners, deals",
    keywords: ["promotions", "promotion hub", "marketing", "campaigns", "offers", "promotional"],
    urduKeywords: ["پروموشن", "مارکیٹنگ", "مہم", "پیشکشیں"],
    romanUrduKeywords: ["promotion", "marketing", "campaign", "paishkashein"],
    category: "Pages", path: "/promotions", icon: Megaphone, group: "Pages",
  },
  {
    id: "page-banners",
    title: "Banners",
    subtitle: "Promotional images and ad banners",
    keywords: ["banners", "ads", "promotions", "advertisements", "images", "slider", "hero"],
    urduKeywords: ["بینرز", "اشتہارات", "پروموشن", "تصاویر"],
    romanUrduKeywords: ["banners", "ishteharaat", "promotion", "ads", "tasaweer"],
    category: "Pages", path: "/banners", icon: Layers, group: "Pages",
  },
  {
    id: "page-popups",
    title: "Popup Campaigns",
    subtitle: "In-app popup notifications and campaigns",
    keywords: ["popups", "popup campaigns", "in-app messages", "interstitial", "modals"],
    urduKeywords: ["پاپ اپ", "کیمپین"],
    romanUrduKeywords: ["popup", "campaign", "in-app"],
    category: "Pages", path: "/popups", icon: Megaphone, group: "Pages",
  },
  {
    id: "page-flash-deals",
    title: "Flash Deals",
    subtitle: "Time-limited discount offers",
    keywords: ["flash deals", "deals", "offers", "discounts", "limited time", "sale", "flash sale"],
    urduKeywords: ["فلیش ڈیلز", "پیشکشیں", "چھوٹ", "خصوصی", "فروخت"],
    romanUrduKeywords: ["flash deals", "paishkashein", "choot", "special offer", "sale"],
    category: "Pages", path: "/flash-deals", icon: Zap, group: "Pages",
  },
  {
    id: "page-promo-codes",
    title: "Promo Codes",
    subtitle: "Discount and coupon codes",
    keywords: ["promo codes", "coupons", "discounts", "vouchers", "referral codes", "promo"],
    urduKeywords: ["پرومو کوڈز", "کوپن", "رعایت", "وائچر"],
    romanUrduKeywords: ["promo codes", "coupon", "riyaayat", "voucher", "discount code"],
    category: "Pages", path: "/promo-codes", icon: Ticket, group: "Pages",
  },
  {
    id: "page-transactions",
    title: "Transactions",
    subtitle: "All financial transactions and wallet history",
    keywords: ["transactions", "payments", "wallet", "history", "transfer", "finance", "payment history"],
    urduKeywords: ["لین دین", "ادائیگیاں", "والیٹ", "تاریخ", "مالیات"],
    romanUrduKeywords: ["lain den", "adaigiyaan", "wallet", "taarikh", "payments", "finance"],
    category: "Pages", path: "/transactions", icon: Receipt, group: "Pages",
  },
  {
    id: "page-withdrawals",
    title: "Withdrawals",
    subtitle: "Rider and vendor payout requests",
    keywords: ["withdrawals", "payout", "cash out", "withdraw", "bank transfer", "pending withdrawals"],
    urduKeywords: ["نکالنا", "ادائیگی", "رقم نکالنا", "بینک ٹرانسفر"],
    romanUrduKeywords: ["nikaalna", "payout", "raqam nikalna", "withdrawal", "bank transfer"],
    category: "Pages", path: "/withdrawals", icon: BanknoteIcon, group: "Pages",
  },
  {
    id: "page-deposits",
    title: "Deposit Requests",
    subtitle: "User wallet top-up requests",
    keywords: ["deposits", "deposit requests", "top up", "recharge", "add money", "wallet recharge"],
    urduKeywords: ["ڈپازٹ", "جمع کرنا", "ری چارج", "پیسے ڈالنا"],
    romanUrduKeywords: ["deposit", "jama karna", "recharge", "paisay dalna", "top up"],
    category: "Pages", path: "/deposit-requests", icon: ArrowDownToLine, group: "Pages",
  },
  {
    id: "page-loyalty",
    title: "Loyalty Points",
    subtitle: "Customer loyalty rewards program",
    keywords: ["loyalty", "points", "rewards", "loyalty program", "earn points", "redeem"],
    urduKeywords: ["وفاداری پوائنٹس", "انعام", "پوائنٹس"],
    romanUrduKeywords: ["loyalty", "points", "rewards", "inaam", "redeem"],
    category: "Pages", path: "/loyalty", icon: Star, group: "Pages",
  },
  {
    id: "page-kyc",
    title: "KYC",
    subtitle: "Identity verification (CNIC, documents)",
    keywords: ["kyc", "verification", "identity", "documents", "cnic", "approved", "rejected", "pending kyc", "know your customer"],
    urduKeywords: ["کے وائی سی", "تصدیق", "شناخت", "دستاویزات", "شناختی کارڈ"],
    romanUrduKeywords: ["kyc", "tasdeeq", "shanaakht", "documents", "cnic", "verification"],
    category: "Pages", path: "/kyc", icon: BadgeCheck, group: "Pages",
  },
  {
    id: "page-wallet-transfers",
    title: "Wallet Transfers",
    subtitle: "Peer-to-peer wallet transfers",
    keywords: ["wallet transfers", "p2p", "send money", "transfer", "wallet", "peer to peer"],
    urduKeywords: ["والیٹ ٹرانسفر", "پیسے بھیجنا", "والیٹ"],
    romanUrduKeywords: ["wallet transfer", "paisay bhejna", "p2p", "send money"],
    category: "Pages", path: "/wallet-transfers", icon: Wallet, group: "Pages",
  },
  {
    id: "page-reviews",
    title: "Reviews",
    subtitle: "Customer reviews and star ratings",
    keywords: ["reviews", "ratings", "feedback", "comments", "stars", "testimonials"],
    urduKeywords: ["جائزے", "درجہ بندی", "تاثرات", "تبصرے", "ستارے"],
    romanUrduKeywords: ["jaizay", "darjabandi", "feedback", "tabsray", "ratings", "sitaray"],
    category: "Pages", path: "/reviews", icon: Star, group: "Pages",
  },
  {
    id: "page-notifications",
    title: "Notifications",
    subtitle: "Push notifications and in-app alerts",
    keywords: ["notifications", "alerts", "push", "messages", "in-app", "notification history"],
    urduKeywords: ["اطلاعات", "الرٹ", "پش", "پیغامات", "اطلاع"],
    romanUrduKeywords: ["ittilaat", "alert", "push", "paighaamaat", "notifications"],
    category: "Pages", path: "/notifications", icon: BellRing, group: "Pages",
  },
  {
    id: "page-broadcast",
    title: "Broadcast",
    subtitle: "Send push notification to all users",
    keywords: ["broadcast", "send notification", "push all", "mass message", "announcement", "notify all"],
    urduKeywords: ["براڈکاسٹ", "اعلان", "پیغام بھیجنا", "سب کو نوٹیفکیشن"],
    romanUrduKeywords: ["broadcast", "ailaan", "paighaam bhejna", "announcement", "mass message"],
    category: "Pages", path: "/broadcast", icon: Megaphone, group: "Pages",
  },
  {
    id: "page-sos",
    title: "SOS Alerts",
    subtitle: "Emergency SOS from users",
    keywords: ["sos", "emergency", "alerts", "help", "danger", "safety", "sos alerts"],
    urduKeywords: ["ایس او ایس", "ہنگامی صورت", "الرٹ", "مدد", "خطرہ"],
    romanUrduKeywords: ["sos", "hangami", "alert", "madad", "khatrah", "emergency"],
    category: "Pages", path: "/sos-alerts", icon: AlertTriangle, group: "Pages",
  },
  {
    id: "page-error-monitor",
    title: "Error Monitor",
    subtitle: "Client error reports and crash logs",
    keywords: ["error monitor", "errors", "crashes", "bug reports", "client errors", "javascript errors"],
    urduKeywords: ["غلطی مانیٹر", "کریش", "غلطیاں"],
    romanUrduKeywords: ["error monitor", "galtiyan", "crash", "bug reports"],
    category: "Pages", path: "/error-monitor", icon: Bug, group: "Pages",
  },
  {
    id: "page-security",
    title: "Security / Audit Logs",
    subtitle: "OTP, MFA, sessions, IP blocking, audit log",
    keywords: ["security", "otp", "mfa", "2fa", "sessions", "ip blocking", "audit log", "login attempts", "lockout", "audit logs"],
    urduKeywords: ["سیکیورٹی", "او ٹی پی", "سیشن", "آئی پی بلاک", "آڈٹ لاگ"],
    romanUrduKeywords: ["security", "otp", "session", "ip block", "audit log", "login"],
    category: "Pages", path: "/security", icon: FileText, group: "Pages",
  },
  {
    id: "page-account-conditions",
    title: "Account Conditions",
    subtitle: "User and vendor account condition rules",
    keywords: ["account conditions", "conditions", "rules", "account rules", "terms"],
    urduKeywords: ["اکاؤنٹ کی شرائط", "شرائط", "قوانین"],
    romanUrduKeywords: ["account conditions", "sharaait", "qawaaneen", "rules"],
    category: "Pages", path: "/account-conditions", icon: Shield, group: "Pages",
  },
  {
    id: "page-condition-rules",
    title: "Condition Rules",
    subtitle: "Dynamic business rules and logic",
    keywords: ["condition rules", "rules", "business logic", "automation", "if-then"],
    urduKeywords: ["حالت کے قوانین", "قوانین", "آٹومیشن"],
    romanUrduKeywords: ["condition rules", "qawaaneen", "automation", "business logic"],
    category: "Pages", path: "/condition-rules", icon: Settings2, group: "Pages",
  },
  {
    id: "page-support-chat",
    title: "Support Chat",
    subtitle: "Customer support conversations",
    keywords: ["support chat", "customer support", "help chat", "live chat", "support tickets"],
    urduKeywords: ["سپورٹ چیٹ", "کسٹمر سپورٹ", "مدد چیٹ"],
    romanUrduKeywords: ["support chat", "customer support", "help chat", "madad chat"],
    category: "Pages", path: "/support-chat", icon: MessageCircle, group: "Pages",
  },
  {
    id: "page-faq",
    title: "FAQ Management",
    subtitle: "Frequently asked questions management",
    keywords: ["faq", "frequently asked questions", "help articles", "knowledge base", "questions"],
    urduKeywords: ["اکثر پوچھے گئے سوالات", "سوالات", "مدد"],
    romanUrduKeywords: ["faq", "aksar sawaalaat", "help articles"],
    category: "Pages", path: "/faq-management", icon: HelpCircle, group: "Pages",
  },
  {
    id: "page-search-analytics",
    title: "Search Analytics",
    subtitle: "What users are searching for in the app",
    keywords: ["search analytics", "analytics", "search trends", "popular searches", "search data"],
    urduKeywords: ["تجزیہ", "تلاش کے رجحانات"],
    romanUrduKeywords: ["search analytics", "tajzia", "trends", "popular searches"],
    category: "Pages", path: "/search-analytics", icon: BarChart2, group: "Pages",
  },
  {
    id: "page-communication",
    title: "Communication",
    subtitle: "Broadcast templates and communication hub",
    keywords: ["communication", "templates", "messaging", "sms campaigns", "email campaigns"],
    urduKeywords: ["مواصلات", "ٹیمپلیٹس", "پیغام رسانی"],
    romanUrduKeywords: ["communication", "templates", "messaging", "campaign"],
    category: "Pages", path: "/communication", icon: Radio, group: "Pages",
  },
  {
    id: "page-chat-monitor",
    title: "Chat Monitor",
    subtitle: "Monitor support conversations",
    keywords: ["chat monitor", "monitor chats", "live conversations", "supervision", "chat oversight"],
    urduKeywords: ["چیٹ مانیٹر", "گفتگو نگرانی"],
    romanUrduKeywords: ["chat monitor", "guftagu nigrani", "supervision"],
    category: "Pages", path: "/chat-monitor", icon: MessageCircle, group: "Pages",
  },
  {
    id: "page-wishlist-insights",
    title: "Wishlist Insights",
    subtitle: "User wishlist and saved items analytics",
    keywords: ["wishlist", "wishlist insights", "saved items", "favorites", "want list"],
    urduKeywords: ["خواہش فہرست", "پسندیدہ اشیاء"],
    romanUrduKeywords: ["wishlist", "khwahish fehrist", "favorites", "saved items"],
    category: "Pages", path: "/wishlist-insights", icon: Heart, group: "Pages",
  },
  {
    id: "page-qr-codes",
    title: "QR Codes",
    subtitle: "Generate and manage QR codes",
    keywords: ["qr codes", "qr", "barcode", "scan", "generate qr"],
    urduKeywords: ["کیو آر کوڈ", "اسکین"],
    romanUrduKeywords: ["qr code", "scan", "barcode"],
    category: "Pages", path: "/qr-codes", icon: QrCode, group: "Pages",
  },
  {
    id: "page-experiments",
    title: "Experiments",
    subtitle: "A/B testing and feature experiments",
    keywords: ["experiments", "a/b testing", "feature flags", "split test", "lab"],
    urduKeywords: ["تجربات", "اے بی ٹیسٹنگ"],
    romanUrduKeywords: ["experiments", "tajrubaat", "a/b testing", "feature flags"],
    category: "Pages", path: "/experiments", icon: FlaskConical, group: "Pages",
  },
  {
    id: "page-webhooks",
    title: "Webhooks",
    subtitle: "Webhook registrations and integrations",
    keywords: ["webhooks", "api webhooks", "integrations", "callbacks", "event hooks"],
    urduKeywords: ["ویب ہکس", "انٹیگریشن"],
    romanUrduKeywords: ["webhooks", "integrations", "callbacks"],
    category: "Pages", path: "/webhooks", icon: Webhook, group: "Pages",
  },
  {
    id: "page-deep-links",
    title: "Deep Links",
    subtitle: "App deep link management",
    keywords: ["deep links", "app links", "universal links", "dynamic links", "routing"],
    urduKeywords: ["ڈیپ لنکس", "ایپ لنکس"],
    romanUrduKeywords: ["deep links", "app links", "universal links"],
    category: "Pages", path: "/deep-links", icon: Link2, group: "Pages",
  },
  {
    id: "page-settings",
    title: "Settings",
    subtitle: "Platform configuration",
    keywords: ["settings", "configuration", "config", "preferences", "setup", "system settings"],
    urduKeywords: ["ترتیبات", "کنفیگریشن", "ترجیحات", "سیٹنگز"],
    romanUrduKeywords: ["tarteebaat", "settings", "configuration", "tarjeehaat", "setup"],
    category: "Pages", path: "/settings", icon: Settings2, group: "Pages",
  },
  {
    id: "page-auth-methods",
    title: "Auth Methods",
    subtitle: "Per-role login methods (Phone, Email, OAuth, 2FA, Biometric)",
    keywords: ["auth methods", "authentication", "login methods", "otp", "oauth", "google login", "facebook login", "magic link", "biometric", "2fa", "two factor", "phone otp", "email otp", "username password", "per-role auth", "customer login", "rider login", "vendor login"],
    urduKeywords: ["لاگ ان", "تصدیق", "او ٹی پی", "گوگل", "فیس بک", "بائیومیٹرک"],
    romanUrduKeywords: ["auth methods", "login methods", "otp", "google login", "facebook login", "magic link", "biometric", "2fa", "phone otp", "email otp"],
    category: "Pages", path: "/auth-methods", icon: KeyRound, group: "Pages",
    hint: "Toggle login methods for Customer, Rider and Vendor",
  },
  {
    id: "page-launch-control",
    title: "Launch Control",
    subtitle: "Pre-launch readiness checklist",
    keywords: ["launch control", "go live", "launch checklist", "readiness", "pre-launch", "production ready"],
    urduKeywords: ["لانچ کنٹرول", "تیاری"],
    romanUrduKeywords: ["launch control", "go live", "checklist", "tayyari"],
    category: "Pages", path: "/launch-control", icon: Settings2, group: "Pages",
  },
  {
    id: "page-otp-control",
    title: "OTP Control",
    subtitle: "OTP delivery providers and policies",
    keywords: ["otp control", "otp provider", "twilio", "sms otp", "email otp", "otp policy", "otp settings"],
    urduKeywords: ["او ٹی پی کنٹرول"],
    romanUrduKeywords: ["otp control", "otp provider", "sms otp"],
    category: "Pages", path: "/otp-control", icon: KeyRound, group: "Pages",
  },
  {
    id: "page-sms-gateways",
    title: "SMS Gateways",
    subtitle: "SMS provider routing and credits",
    keywords: ["sms gateways", "sms provider", "twilio", "jazz", "telenor", "sms routing", "sms credits"],
    urduKeywords: ["ایس ایم ایس گیٹ ویز"],
    romanUrduKeywords: ["sms gateways", "sms provider"],
    category: "Pages", path: "/sms-gateways", icon: Settings2, group: "Pages",
  },
  {
    id: "page-app-management",
    title: "App Management / Feature Toggles",
    subtitle: "Version, maintenance, feature flags",
    keywords: ["app management", "version", "update", "maintenance", "app status", "feature toggles", "enable disable features"],
    urduKeywords: ["ایپ مینجمنٹ", "ورژن", "اپ ڈیٹ", "ایپ کی حالت", "فیچر"],
    romanUrduKeywords: ["app management", "version", "update", "feature toggles", "maintenance"],
    category: "Pages", path: "/app-management", icon: ToggleLeft, group: "Pages",
  },
  {
    id: "page-delivery-access",
    title: "Delivery Access",
    subtitle: "Delivery zone and access control",
    keywords: ["delivery access", "delivery zones", "access control", "zone management", "delivery areas"],
    urduKeywords: ["ڈیلیوری رسائی", "ڈیلیوری زون"],
    romanUrduKeywords: ["delivery access", "delivery zones", "rasaai"],
    category: "Pages", path: "/delivery-access", icon: Truck, group: "Pages",
  },

  /* ════════════════════ SETTINGS SECTIONS ════════════════════ */
  {
    id: "settings-general",
    title: "Settings → General",
    subtitle: "App name, logo, tagline, maintenance mode",
    keywords: ["general settings", "app name", "logo", "tagline", "app status", "maintenance mode", "branding", "app title"],
    urduKeywords: ["عمومی ترتیبات", "ایپ کا نام", "لوگو", "ٹیگ لائن", "بحالی"],
    romanUrduKeywords: ["general settings", "app name", "logo", "tagline", "maintenance", "branding"],
    category: "Settings", path: "/settings", icon: Settings2, group: "Settings",
    hint: "App name, logo, tagline, maintenance mode",
  },
  {
    id: "settings-ride-pricing",
    title: "Settings → Ride Pricing",
    subtitle: "Base fares, per-km rates, surge, bargaining",
    keywords: ["ride pricing", "fare", "bike fare", "car fare", "rickshaw", "bargaining", "surge", "base fare", "per km", "ride rates"],
    urduKeywords: ["سواری کی قیمت", "کرایہ", "بائیک کرایہ", "گاڑی کرایہ", "رکشہ", "مول تول"],
    romanUrduKeywords: ["sawari ki qeemat", "kiraya", "bike kiraya", "gaari kiraya", "riksha", "moltol", "bargaining", "surge"],
    category: "Settings", path: "/settings", icon: Car, group: "Settings",
    hint: "Base fares, per-km rates, surge multiplier",
  },
  {
    id: "settings-payment",
    title: "Settings → Payment",
    subtitle: "JazzCash, EasyPaisa, COD, wallet toggles",
    keywords: ["payment", "jazzcash", "easypaisa", "cod", "cash on delivery", "wallet", "payment methods", "online payment", "payment gateway"],
    urduKeywords: ["ادائیگی", "جیز کیش", "ایزی پیسہ", "نقد", "والیٹ", "ادائیگی کے طریقے"],
    romanUrduKeywords: ["adaigi", "jazzcash", "easypaisa", "cod", "naqdh", "wallet", "payment"],
    category: "Settings", path: "/settings", icon: Receipt, group: "Settings",
    hint: "JazzCash, EasyPaisa, COD, wallet settings",
  },
  {
    id: "settings-orders",
    title: "Settings → Orders",
    subtitle: "Delivery radius, cart limits, order rules",
    keywords: ["order settings", "delivery rules", "cart limit", "minimum order", "delivery radius", "order rules", "scheduling"],
    urduKeywords: ["آرڈر کی ترتیبات", "ڈیلیوری کے قوانین", "کارٹ کی حد", "کم از کم آرڈر"],
    romanUrduKeywords: ["order settings", "delivery rules", "cart limit", "minimum order", "delivery radius"],
    category: "Settings", path: "/settings", icon: ShoppingBag, group: "Settings",
    hint: "Delivery radius, cart limits, scheduling",
  },
  {
    id: "settings-finance",
    title: "Settings → Finance",
    subtitle: "Commission rates, GST, rider/vendor payouts",
    keywords: ["finance", "commission", "rider commission", "vendor commission", "payout", "gst", "tax", "earnings", "profit"],
    urduKeywords: ["مالیات", "کمیشن", "رائیڈر کا حصہ", "ادائیگی", "ٹیکس", "کمائی"],
    romanUrduKeywords: ["maaliyaat", "commission", "rider ka hissa", "payout", "tax", "gst", "kamaai"],
    category: "Settings", path: "/settings", icon: Banknote, group: "Settings",
    hint: "Commission, GST, payout settings",
  },
  {
    id: "settings-security",
    title: "Settings → Security",
    subtitle: "OTP config, login lockout, IP whitelist",
    keywords: ["security settings", "otp settings", "mfa", "2fa", "session expiry", "ip whitelist", "login lockout", "otp cooldown"],
    urduKeywords: ["سیکیورٹی کی ترتیبات", "او ٹی پی", "سیشن", "آئی پی وائٹ لسٹ"],
    romanUrduKeywords: ["security settings", "otp", "mfa", "session expiry", "ip whitelist", "login lockout"],
    category: "Settings", path: "/security", icon: Shield, group: "Settings",
    hint: "OTP, MFA, session expiry, IP whitelist",
  },
  {
    id: "settings-features",
    title: "Settings → Features",
    subtitle: "Enable/disable app features",
    keywords: ["features", "feature toggle", "rides toggle", "wallet toggle", "mart toggle", "food toggle", "parcel toggle", "pharmacy toggle", "enable", "disable", "feature flags"],
    urduKeywords: ["خصوصیات", "فیچر آن آف", "سواری", "والیٹ", "مارٹ"],
    romanUrduKeywords: ["features", "feature toggle", "sawari", "wallet", "mart", "enable", "disable", "band karna"],
    category: "Settings", path: "/app-management", icon: Zap, group: "Settings",
    hint: "Toggle rides, wallet, mart, food, parcel, pharmacy",
  },
  {
    id: "settings-notifications",
    title: "Settings → Notifications",
    subtitle: "FCM, SMS gateway, WhatsApp OTP",
    keywords: ["notification settings", "fcm", "firebase", "sms", "push notifications", "email alerts", "whatsapp", "smtp"],
    urduKeywords: ["اطلاع کی ترتیبات", "ایف سی ایم", "ایس ایم ایس", "پش نوٹیفکیشن", "واٹس ایپ"],
    romanUrduKeywords: ["notification settings", "fcm", "firebase", "sms", "push", "email", "whatsapp"],
    category: "Settings", path: "/settings", icon: BellRing, group: "Settings",
    hint: "FCM server key, SMS, WhatsApp OTP",
  },
  {
    id: "settings-maps",
    title: "Settings → Maps",
    subtitle: "Google Maps, Mapbox, LocationIQ API keys",
    keywords: ["maps settings", "google maps", "mapbox", "locationiq", "api key", "geocoding", "maps provider"],
    urduKeywords: ["میپ کی ترتیبات", "گوگل میپ"],
    romanUrduKeywords: ["maps settings", "google maps", "mapbox", "api key", "geocoding"],
    category: "Settings", path: "/settings", icon: Navigation, group: "Settings",
    hint: "Google Maps, Mapbox, LocationIQ config",
  },
  {
    id: "settings-integrations",
    title: "Settings → Integrations",
    subtitle: "SMTP, SMS gateway, Firebase, WhatsApp config",
    keywords: ["integrations", "smtp", "email config", "sms config", "whatsapp config", "firebase", "api integration"],
    urduKeywords: ["انٹیگریشن", "ای میل کنفیگ", "ایس ایم ایس"],
    romanUrduKeywords: ["integrations", "smtp", "email config", "sms config", "firebase"],
    category: "Settings", path: "/settings", icon: Settings2, group: "Settings",
    hint: "Email, SMS, WhatsApp, Firebase integration config",
  },

  /* ════════════════════ QUICK ACTIONS ════════════════════ */
  {
    id: "action-live-rides",
    title: "Live Rides & Orders",
    subtitle: "Real-time bargaining and searching rides",
    keywords: ["live rides", "active rides", "live orders", "bargaining", "searching", "real-time", "monitor"],
    urduKeywords: ["لائیو سواریاں", "فعال سواریاں", "لائیو آرڈرز", "مول تول"],
    romanUrduKeywords: ["live rides", "active rides", "live orders", "moltol", "real-time"],
    category: "Actions", path: "/rides", icon: Car, group: "Quick Actions",
    hint: "Monitor live rides and bargaining",
  },
  {
    id: "action-send-broadcast",
    title: "Send Broadcast",
    subtitle: "Push notification to all users",
    keywords: ["send broadcast", "send notification", "push all users", "announcement", "mass message", "notify"],
    urduKeywords: ["براڈکاسٹ بھیجیں", "سب کو نوٹیفکیشن", "اعلان"],
    romanUrduKeywords: ["broadcast bhejna", "sab ko notification", "ailaan", "mass message"],
    category: "Actions", path: "/broadcast", icon: Megaphone, group: "Quick Actions",
    hint: "Send push notification to all users",
  },
  {
    id: "action-add-promo",
    title: "Add Promo Code",
    subtitle: "Create a new discount coupon",
    keywords: ["add promo", "create coupon", "new discount", "promo code", "voucher", "new promo"],
    urduKeywords: ["پرومو کوڈ شامل کریں", "کوپن بنائیں", "چھوٹ بنائیں"],
    romanUrduKeywords: ["promo code shamil karo", "coupon banao", "choot banao", "new promo"],
    category: "Actions", path: "/promo-codes", icon: Ticket, group: "Quick Actions",
    hint: "Create a new discount coupon",
  },
  {
    id: "action-add-flash-deal",
    title: "Add Flash Deal",
    subtitle: "Create a time-limited offer",
    keywords: ["add flash deal", "create deal", "flash sale", "time-limited offer", "special offer", "new deal"],
    urduKeywords: ["فلیش ڈیل شامل کریں", "ڈیل بنائیں", "خصوصی پیشکش"],
    romanUrduKeywords: ["flash deal shamil karo", "deal banao", "special paishkash", "sale"],
    category: "Actions", path: "/flash-deals", icon: Zap, group: "Quick Actions",
    hint: "Create a time-limited special offer",
  },
  {
    id: "action-pending-orders",
    title: "Pending Orders",
    subtitle: "Orders waiting to be confirmed",
    keywords: ["pending orders", "waiting orders", "unconfirmed", "new orders", "open orders"],
    urduKeywords: ["زیر التواء آرڈرز", "انتظار میں آرڈرز", "نئے آرڈرز"],
    romanUrduKeywords: ["zer-e-iltawa orders", "pending orders", "intizar orders", "naye orders"],
    category: "Actions", path: "/orders?status=pending", icon: ShoppingBag, group: "Quick Actions",
    hint: "View orders with pending status",
  },
  {
    id: "action-cancelled-orders",
    title: "Cancelled Orders",
    subtitle: "Orders that were cancelled",
    keywords: ["cancelled orders", "canceled orders", "failed orders"],
    urduKeywords: ["منسوخ آرڈرز"],
    romanUrduKeywords: ["mansookh orders", "cancelled orders"],
    category: "Actions", path: "/orders?status=cancelled", icon: ShoppingBag, group: "Quick Actions",
    hint: "View orders with cancelled status",
  },
  {
    id: "action-searching-rides",
    title: "Searching Rides",
    subtitle: "Rides currently looking for a driver",
    keywords: ["searching rides", "active rides", "live rides", "open rides", "unmatched"],
    urduKeywords: ["تلاش کرتی سواریاں", "فعال سواریاں"],
    romanUrduKeywords: ["searching rides", "active rides", "live rides", "talash"],
    category: "Actions", path: "/rides?status=searching", icon: Car, group: "Quick Actions",
    hint: "Rides searching for a driver",
  },
  {
    id: "action-bargaining-rides",
    title: "Bargaining Rides",
    subtitle: "Rides in fare negotiation",
    keywords: ["bargaining rides", "negotiating", "fare negotiation", "moltol"],
    urduKeywords: ["مول تول سواریاں", "مول بھاؤ"],
    romanUrduKeywords: ["moltol sawariyan", "bargaining rides", "fare negotiation"],
    category: "Actions", path: "/rides?status=bargaining", icon: Car, group: "Quick Actions",
    hint: "Rides in bargaining stage",
  },
  {
    id: "action-cancelled-rides",
    title: "Cancelled Rides",
    subtitle: "Rides that were cancelled",
    keywords: ["cancelled rides", "canceled rides", "failed rides"],
    urduKeywords: ["منسوخ سواریاں"],
    romanUrduKeywords: ["mansookh sawariyan", "cancelled rides"],
    category: "Actions", path: "/rides?status=cancelled", icon: Car, group: "Quick Actions",
    hint: "View cancelled rides",
  },
  {
    id: "action-pending-kyc",
    title: "Pending KYC",
    subtitle: "KYC submissions awaiting review",
    keywords: ["pending kyc", "pending verification", "unreviewed documents", "cnic pending"],
    urduKeywords: ["زیر التواء کے وائی سی", "زیر التواء تصدیق"],
    romanUrduKeywords: ["pending kyc", "pending tasdeeq", "unreviewed"],
    category: "Actions", path: "/kyc?status=pending", icon: BadgeCheck, group: "Quick Actions",
    hint: "Review pending KYC submissions",
  },
  {
    id: "action-pending-withdrawals",
    title: "Pending Withdrawals",
    subtitle: "Withdrawal requests awaiting approval",
    keywords: ["pending withdrawals", "withdrawal requests", "payout pending", "unpaid"],
    urduKeywords: ["زیر التواء نکالنا", "ادائیگی انتظار"],
    romanUrduKeywords: ["pending nikaalna", "withdrawal pending", "payout intizar"],
    category: "Actions", path: "/withdrawals?status=pending", icon: BanknoteIcon, group: "Quick Actions",
    hint: "Approve pending withdrawal requests",
  },
  {
    id: "action-search-users",
    title: "Search Users",
    subtitle: "Find a user by phone, name or email",
    keywords: ["search user", "find user", "look up user", "user lookup", "find customer"],
    urduKeywords: ["صارف ڈھونڈیں", "صارف تلاش"],
    romanUrduKeywords: ["user dhundho", "find user", "talash user"],
    category: "Actions", path: "/users", icon: Search, group: "Quick Actions",
    hint: "Find users by name, phone, or email",
  },
  {
    id: "action-banned-users",
    title: "Banned Users",
    subtitle: "Users who have been banned",
    keywords: ["banned users", "blocked users", "suspended", "deactivated"],
    urduKeywords: ["پابندی شدہ صارفین", "بند صارفین"],
    romanUrduKeywords: ["banned users", "blocked users", "pabandi", "band"],
    category: "Actions", path: "/users?filter=banned", icon: Lock, group: "Quick Actions",
    hint: "View banned/suspended users",
  },
];

/** Derive a Set of all valid IDs for AI prompt validation */
export const SEARCH_INDEX_IDS = new Set(SEARCH_INDEX.map(e => e.id));
