// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/wallet-redesign/BoldGradient.tsx": () => import("../components/mockups/wallet-redesign/BoldGradient.tsx"),
  "./components/mockups/wallet-redesign/GlassmorphismPremium.tsx": () => import("../components/mockups/wallet-redesign/GlassmorphismPremium.tsx"),
  "./components/mockups/wallet-redesign/NeobankMinimal.tsx": () => import("../components/mockups/wallet-redesign/NeobankMinimal.tsx")
};
