-- Migration: Initial schema — creates core tables required before any ALTER TABLE migrations
-- Uses CREATE TABLE IF NOT EXISTS so it is safe to run on existing databases.

CREATE TABLE IF NOT EXISTS users (
  id                          text PRIMARY KEY,
  phone                       text UNIQUE,
  name                        text,
  email                       text UNIQUE,
  roles                       text NOT NULL DEFAULT 'customer',
  avatar                      text,
  wallet_balance              decimal(10, 2) NOT NULL DEFAULT 0,
  otp_code                    text,
  otp_expiry                  timestamp,
  otp_used                    boolean NOT NULL DEFAULT false,
  email_otp_code              text,
  email_otp_expiry            timestamp,
  username                    text UNIQUE,
  password_hash               text,
  require_password_change     boolean NOT NULL DEFAULT false,
  phone_verified              boolean NOT NULL DEFAULT false,
  email_verified              boolean NOT NULL DEFAULT false,
  approval_status             text NOT NULL DEFAULT 'approved',
  approval_note               text,
  is_active                   boolean NOT NULL DEFAULT true,
  is_banned                   boolean NOT NULL DEFAULT false,
  ban_reason                  text,
  blocked_services            text NOT NULL DEFAULT '',
  security_note               text,
  is_online                   boolean NOT NULL DEFAULT false,
  cnic                        text,
  address                     text,
  city                        text,
  area                        text,
  latitude                    text,
  longitude                   text,
  kyc_status                  text NOT NULL DEFAULT 'none',
  account_level               text NOT NULL DEFAULT 'bronze',
  emergency_contact           text,
  bank_name                   text,
  bank_account                text,
  bank_account_title          text,
  national_id                 text,
  biometric_enabled           boolean NOT NULL DEFAULT false,
  wallet_pin_hash             text,
  wallet_pin_attempts         integer NOT NULL DEFAULT 0,
  wallet_pin_locked_until     timestamp,
  wallet_hidden               boolean NOT NULL DEFAULT false,
  mpin_reset_pending_at       timestamp,
  mpin_reset_new_hash_pending text,
  totp_secret                 text,
  totp_enabled                boolean NOT NULL DEFAULT false,
  backup_codes                text,
  trusted_devices             text,
  firebase_uid                text UNIQUE,
  google_id                   text UNIQUE,
  facebook_id                 text UNIQUE,
  cancel_count                integer NOT NULL DEFAULT 0,
  ignore_count                integer NOT NULL DEFAULT 0,
  is_restricted               boolean NOT NULL DEFAULT false,
  cancellation_debt           decimal(10, 2) NOT NULL DEFAULT 0,
  merge_otp_code              text,
  merge_otp_expiry            timestamp,
  pending_merge_identifier    text,
  device_id                   text,
  token_version               integer NOT NULL DEFAULT 0,
  dev_otp_enabled             boolean NOT NULL DEFAULT false,
  otp_bypass_until            timestamp,
  cancellation_rate           decimal(5, 2) NOT NULL DEFAULT 0,
  fraud_incidents             integer NOT NULL DEFAULT 0,
  abuse_reports               integer NOT NULL DEFAULT 0,
  miss_ignore_rate            decimal(5, 2) NOT NULL DEFAULT 0,
  order_completion_rate       decimal(5, 2) NOT NULL DEFAULT 100,
  avg_rating                  decimal(3, 2),
  auto_suspended_at           timestamp,
  auto_suspend_reason         text,
  admin_override_suspension   boolean NOT NULL DEFAULT false,
  commission_override         text,
  ajk_id                      text UNIQUE,
  chat_muted                  boolean NOT NULL DEFAULT false,
  comm_blocked                boolean NOT NULL DEFAULT false,
  last_login_at               timestamp,
  last_active                 timestamp,
  accepted_terms_version      text,
  created_at                  timestamp NOT NULL DEFAULT now(),
  updated_at                  timestamp NOT NULL DEFAULT now(),
  CONSTRAINT users_wallet_non_negative CHECK (wallet_balance >= 0)
);

CREATE INDEX IF NOT EXISTS users_roles_idx ON users (roles);
CREATE INDEX IF NOT EXISTS users_is_online_idx ON users (is_online);
CREATE INDEX IF NOT EXISTS users_roles_is_online_idx ON users (roles, is_online);
CREATE INDEX IF NOT EXISTS users_ajk_id_idx ON users (ajk_id);
