ALTER TABLE orders ADD COLUMN IF NOT EXISTS customer_lat DECIMAL(10,7);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS customer_lng DECIMAL(10,7);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS gps_accuracy DOUBLE PRECISION;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS gps_mismatch BOOLEAN DEFAULT FALSE;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_lat DECIMAL(10,7);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_lng DECIMAL(10,7);
